# setup environment
sudo: false
language: python
cache: pip

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-ansible"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

os:
  global: linux

matrix:
  include:
    - env: ATOM_CHANNEL=stable
    - env: ATOM_CHANNEL=beta

# execute tests
install: pip install ansible
before_script: ansible --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
